### ISSUE TITLE
【footer】ご利用規約、プライバシーポリシー、運営会社の中身

### ISSUE THREAD

**Issue by yuma-itano** [Aki130238/brandfunding#135]

**Comment by Aki130238** [comment]
運営会社の中身
ノアコネクトのチーム紹介
チーム：ノアコネクト（NoIdea(アイデア) x NoArt(技) をconnect(繋ぐ)）
DEMODAY予選突破を機に７月期受講生だけでチームを発足。
井関　旭：チーム発起人。起業経験を生かしたビジネスアイディアで優勝を目指す。
板野 侑真：Railsを学ぶ中でフロントに惹かれ独習。バックもフロントもこなせるマルチエンジニア。
荒牧 拓実：７月期最速でカリキュラムを終えた実力者。未経験から１ヶ月でRailsをマスター。
平井 裕二：独自の学習スタイルでRailsを深く理解する実力者。チーム開発でも欠かせない中心的存在。
堀川 設男：Railsだけでなくその周辺知識を網羅。圧倒的な知識量でwebサービスの方向性を導く。
